// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2LMt_NQwJko6DGEF8FilzjSfLfFKYt6g',
    appId: '1:951493717912:web:73086298a1b4973a93c5ed',
    messagingSenderId: '951493717912',
    projectId: 'fir-flutter-codelab-83a9e',
    authDomain: 'fir-flutter-codelab-83a9e.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-83a9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPG_GaEzoh8uZ2GnDAQKM5RCINCrPm-So',
    appId: '1:951493717912:android:c4043a7b5576f15093c5ed',
    messagingSenderId: '951493717912',
    projectId: 'fir-flutter-codelab-83a9e',
    storageBucket: 'fir-flutter-codelab-83a9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF7jZaacqoOPLBSkoImW--cFEPFAzr2Ds',
    appId: '1:951493717912:ios:6fd0df4550dbc35293c5ed',
    messagingSenderId: '951493717912',
    projectId: 'fir-flutter-codelab-83a9e',
    storageBucket: 'fir-flutter-codelab-83a9e.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF7jZaacqoOPLBSkoImW--cFEPFAzr2Ds',
    appId: '1:951493717912:ios:6fd0df4550dbc35293c5ed',
    messagingSenderId: '951493717912',
    projectId: 'fir-flutter-codelab-83a9e',
    storageBucket: 'fir-flutter-codelab-83a9e.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
