// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqY4bVmE33f6ums7I-LLgs8ktdkIALum4',
    appId: '1:871070502377:web:36a2679c3e1eb7b2d6cf78',
    messagingSenderId: '871070502377',
    projectId: 'grage-8aed2',
    authDomain: 'grage-8aed2.firebaseapp.com',
    storageBucket: 'grage-8aed2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh-NH8hU5ZzZRmhAJW7UkxajCSw2tYSTQ',
    appId: '1:871070502377:android:af793b5edbfdf386d6cf78',
    messagingSenderId: '871070502377',
    projectId: 'grage-8aed2',
    storageBucket: 'grage-8aed2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8w5MWA0riqXFjg6F-kbQmHPZA4WCw52Q',
    appId: '1:871070502377:ios:920914c1641c7cded6cf78',
    messagingSenderId: '871070502377',
    projectId: 'grage-8aed2',
    storageBucket: 'grage-8aed2.appspot.com',
    iosBundleId: 'com.example.info6350FinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8w5MWA0riqXFjg6F-kbQmHPZA4WCw52Q',
    appId: '1:871070502377:ios:920914c1641c7cded6cf78',
    messagingSenderId: '871070502377',
    projectId: 'grage-8aed2',
    storageBucket: 'grage-8aed2.appspot.com',
    iosBundleId: 'com.example.info6350FinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqY4bVmE33f6ums7I-LLgs8ktdkIALum4',
    appId: '1:871070502377:web:12126c300314999fd6cf78',
    messagingSenderId: '871070502377',
    projectId: 'grage-8aed2',
    authDomain: 'grage-8aed2.firebaseapp.com',
    storageBucket: 'grage-8aed2.appspot.com',
  );

}